name: Restart Router on Cloud Run

on:
  # push:
  #   paths:
  #     - '**.yaml'
  workflow_dispatch:
  workflow_call:
  # repository_dispatch:
  #   types: [update-router-event]

env:
  GEN: ${{ secrets.GEN || 'ws1' }}

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - id: 'auth'
        uses: 'google-github-actions/auth@v2.1.4'
        with:
          credentials_json: ${{ secrets.GCP_CREDENTIALS }}

      # - name: Add Secret data
      #   run: gcloud secrets versions add --data-file=./router/router.yaml ${{vars.ACTOR}}

      # - name: Redeploy Cloud Run Service
      #   run: |
      #     gcloud run services update ${{vars.ACTOR}}-router \
      #       --platform managed \
      #       --region us-central1 \
      #       --quiet

      - name: Redeploy Apollo Router to Cloud Run
        run: |
          gcloud run services update ${{vars.ACTOR}}-router --image gcr.io/summit-enterprise-workshop/router-v2_0-preview:latest \
            --command=/dist/router \
            --set-secrets=/dist/config/router.yaml=${{vars.ACTOR}}:latest \
            --set-env-vars "APOLLO_ROUTER_LOG=debug,APOLLO_ROUTER_HOT_RELOAD=false,APOLLO_KEY=${{ vars.TOKEN }},APOLLO_GRAPH_REF=${{vars.ACTOR}}${{env.GEN}}@current" --platform managed --region us-central1
